//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumenty
    {
        public string Наименование { get; set; }
        public string Описание { get; set; }
        public string Тип_инструмента { get; set; }
        public string Возраст__в_месяцах_ { get; set; }
        public string Количество { get; set; }
        public string Степень_износа { get; set; }
        public int ID { get; set; }
    }
}
