//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdeliye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izdeliye()
        {
            this.Zakaz = new HashSet<Zakaz>();
            this.Spetsifikatsiya_ingrediyenty = new HashSet<Spetsifikatsiya_ingrediyenty>();
            this.Spetsifikatsiya_operatsii = new HashSet<Spetsifikatsiya_operatsii>();
            this.Spetsifikatsiya_polufabrikaty = new HashSet<Spetsifikatsiya_polufabrikaty>();
            this.Spetsifikatsiya_polufabrikaty1 = new HashSet<Spetsifikatsiya_polufabrikaty>();
            this.Spetsifikatsiya_ukrasheniya_dlya_torta = new HashSet<Spetsifikatsiya_ukrasheniya_dlya_torta>();
        }
    
        public string Наименование { get; set; }
        public string Размер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spetsifikatsiya_ingrediyenty> Spetsifikatsiya_ingrediyenty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spetsifikatsiya_operatsii> Spetsifikatsiya_operatsii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spetsifikatsiya_polufabrikaty> Spetsifikatsiya_polufabrikaty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spetsifikatsiya_polufabrikaty> Spetsifikatsiya_polufabrikaty1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spetsifikatsiya_ukrasheniya_dlya_torta> Spetsifikatsiya_ukrasheniya_dlya_torta { get; set; }
    }
}
