//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavishchik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavishchik()
        {
            this.Ingrediyent = new HashSet<Ingrediyent>();
            this.Ukrasheniye_dlya_torta = new HashSet<Ukrasheniye_dlya_torta>();
        }
    
        public string Название_поставщика { get; set; }
        public string Адрес { get; set; }
        public System.DateTime Срок_доставки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingrediyent> Ingrediyent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ukrasheniye_dlya_torta> Ukrasheniye_dlya_torta { get; set; }
    }
}
