//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spetsifikatsiya_ukrasheniya_dlya_torta
    {
        public string Изделие { get; set; }
        public string Украшение_для_торта { get; set; }
        public int Кол_во { get; set; }
    
        public virtual Izdeliye Izdeliye { get; set; }
        public virtual Ukrasheniye_dlya_torta Ukrasheniye_dlya_torta { get; set; }
    }
}
