//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spetsifikatsiya_operatsii
    {
        public string Изделие { get; set; }
        public string Операция { get; set; }
        public int Порядковый_номер { get; set; }
        public string Тип_оборудования { get; set; }
        public System.TimeSpan Время_на_операцию { get; set; }
    
        public virtual Izdeliye Izdeliye { get; set; }
        public virtual Tip_Oborudovaniye Tip_Oborudovaniye { get; set; }
    }
}
